[2025-03-22T06:56:32.103+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: job_data_stream.job_data_stream manual__2025-03-22T06:41:17.406337+00:00 [queued]>
[2025-03-22T06:56:32.115+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: job_data_stream.job_data_stream manual__2025-03-22T06:41:17.406337+00:00 [queued]>
[2025-03-22T06:56:32.119+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-22T06:56:32.134+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): job_data_stream> on 2025-03-22 06:41:17.406337+00:00
[2025-03-22T06:56:32.141+0000] {standard_task_runner.py:57} INFO - Started process 54 to run task
[2025-03-22T06:56:32.145+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'job_data_stream', 'job_data_stream', 'manual__2025-03-22T06:41:17.406337+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/data_stream.py', '--cfg-path', '/tmp/tmpf9k_1okh']
[2025-03-22T06:56:32.146+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask job_data_stream
[2025-03-22T06:56:32.212+0000] {task_command.py:415} INFO - Running <TaskInstance: job_data_stream.job_data_stream manual__2025-03-22T06:41:17.406337+00:00 [running]> on host 752d2ff73c15
[2025-03-22T06:56:32.310+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dii' AIRFLOW_CTX_DAG_ID='job_data_stream' AIRFLOW_CTX_TASK_ID='job_data_stream' AIRFLOW_CTX_EXECUTION_DATE='2025-03-22T06:41:17.406337+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-22T06:41:17.406337+00:00'
[2025-03-22T06:56:32.388+0000] {conn.py:1542} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-03-22T06:56:32.389+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-03-22T06:56:32.389+0000] {conn.py:1219} INFO - Probing node bootstrap-0 broker version
[2025-03-22T06:56:32.403+0000] {conn.py:1542} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-03-22T06:56:32.404+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-03-22T06:56:32.419+0000] {conn.py:1542} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-03-22T06:56:32.420+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-03-22T06:56:32.422+0000] {conn.py:1219} INFO - Probing node bootstrap-0 broker version
[2025-03-22T06:56:32.441+0000] {conn.py:1542} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-03-22T06:56:32.443+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-03-22T06:56:32.445+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_stream.py", line 31, in stream_data
    producer = KafkaProducer(bootstrap_servers=['broker:29092'])
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 383, in __init__
    client = self.config['kafka_client'](
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 241, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 918, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-03-22T06:56:32.514+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=job_data_stream, task_id=job_data_stream, execution_date=20250322T064117, start_date=20250322T065632, end_date=20250322T065632
[2025-03-22T06:56:32.551+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task job_data_stream (NoBrokersAvailable; 54)
[2025-03-22T06:56:32.580+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-22T06:56:32.639+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
