[2025-03-12T06:36:58.273+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: job_data_stream.job_data_stream scheduled__2025-03-11T00:00:00+00:00 [queued]>
[2025-03-12T06:36:58.285+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: job_data_stream.job_data_stream scheduled__2025-03-11T00:00:00+00:00 [queued]>
[2025-03-12T06:36:58.285+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-12T06:36:58.300+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): job_data_stream> on 2025-03-11 00:00:00+00:00
[2025-03-12T06:36:58.304+0000] {standard_task_runner.py:57} INFO - Started process 52 to run task
[2025-03-12T06:36:58.308+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'job_data_stream', 'job_data_stream', 'scheduled__2025-03-11T00:00:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/data_stream.py', '--cfg-path', '/tmp/tmpj85kqdk8']
[2025-03-12T06:36:58.309+0000] {standard_task_runner.py:85} INFO - Job 85: Subtask job_data_stream
[2025-03-12T06:36:58.384+0000] {task_command.py:415} INFO - Running <TaskInstance: job_data_stream.job_data_stream scheduled__2025-03-11T00:00:00+00:00 [running]> on host 0431913abdf0
[2025-03-12T06:36:58.486+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dii' AIRFLOW_CTX_DAG_ID='job_data_stream' AIRFLOW_CTX_TASK_ID='job_data_stream' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-11T00:00:00+00:00'
[2025-03-12T06:36:58.554+0000] {conn.py:1542} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-03-12T06:36:58.556+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-03-12T06:36:58.557+0000] {conn.py:1219} INFO - Probing node bootstrap-0 broker version
[2025-03-12T06:36:58.579+0000] {conn.py:1542} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-03-12T06:36:58.580+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-03-12T06:36:58.603+0000] {conn.py:1542} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-03-12T06:36:58.604+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-03-12T06:36:58.605+0000] {conn.py:1219} INFO - Probing node bootstrap-0 broker version
[2025-03-12T06:36:58.620+0000] {conn.py:1542} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-03-12T06:36:58.621+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-03-12T06:36:58.622+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_stream.py", line 31, in stream_data
    producer = KafkaProducer(bootstrap_servers=['broker:29092'])
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 383, in __init__
    client = self.config['kafka_client'](
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 241, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 918, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-03-12T06:36:58.642+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=job_data_stream, task_id=job_data_stream, execution_date=20250311T000000, start_date=20250312T063658, end_date=20250312T063658
[2025-03-12T06:36:58.654+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 85 for task job_data_stream (NoBrokersAvailable; 52)
[2025-03-12T06:36:58.691+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-12T06:36:58.709+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
