[2025-03-09T02:55:44.187+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stream_data.stream_data scheduled__2025-03-08T00:00:00+00:00 [queued]>
[2025-03-09T02:55:44.205+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stream_data.stream_data scheduled__2025-03-08T00:00:00+00:00 [queued]>
[2025-03-09T02:55:44.205+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-09T02:55:44.229+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): stream_data> on 2025-03-08 00:00:00+00:00
[2025-03-09T02:55:44.235+0000] {standard_task_runner.py:57} INFO - Started process 52 to run task
[2025-03-09T02:55:44.240+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stream_data', 'stream_data', 'scheduled__2025-03-08T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/data_stream.py', '--cfg-path', '/tmp/tmpi0jqe4n3']
[2025-03-09T02:55:44.243+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask stream_data
[2025-03-09T02:55:44.362+0000] {task_command.py:415} INFO - Running <TaskInstance: stream_data.stream_data scheduled__2025-03-08T00:00:00+00:00 [running]> on host 490145d03e49
[2025-03-09T02:55:44.564+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dii' AIRFLOW_CTX_DAG_ID='stream_data' AIRFLOW_CTX_TASK_ID='stream_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-08T00:00:00+00:00'
[2025-03-09T02:55:44.579+0000] {conn.py:384} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]>: connecting to broker:29092 [('172.18.0.9', 29092) IPv4]
[2025-03-09T02:55:44.582+0000] {conn.py:1219} INFO - Probing node bootstrap-0 broker version
[2025-03-09T02:55:44.590+0000] {conn.py:422} ERROR - Connect attempt to <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]> returned error 111. Disconnecting.
[2025-03-09T02:55:44.594+0000] {conn.py:928} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-03-09T02:55:44.596+0000] {conn.py:384} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]>: connecting to broker:29092 [('172.18.0.9', 29092) IPv4]
[2025-03-09T02:55:44.597+0000] {conn.py:422} ERROR - Connect attempt to <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]> returned error 111. Disconnecting.
[2025-03-09T02:55:44.598+0000] {conn.py:928} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-03-09T02:55:44.600+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_stream.py", line 31, in stream_data
    producer = KafkaProducer(bootstrap_servers=['broker:29092'])
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 383, in __init__
    client = self.config['kafka_client'](
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 241, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 918, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-03-09T02:55:44.630+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=stream_data, task_id=stream_data, execution_date=20250308T000000, start_date=20250309T025544, end_date=20250309T025544
[2025-03-09T02:55:44.654+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task stream_data (NoBrokersAvailable; 52)
[2025-03-09T02:55:44.710+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-09T02:55:44.746+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
